require: 'rubocop-rspec'

AllCops:
  NewCops: enable
  Include:
    - '**/Rakefile'
    - "**/*_spec.rb"
    - "**/spec/**/*"

Style/Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/Encoding:
  Enabled: false